# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel

sudo: false
cache: packages

warnings_are_errors: false

before_install:
  - mkdir -p ~/.R
  - echo -e 'MAKEFLAGS = -j2' > ~/.R/Makevars
  - echo 'options(Ncpus = 2)' > ~/.Rprofile
  - Rscript -e 'remotes::install_deps(dependencies = TRUE)'

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

r_packages:
  - remotes
  - BiocManager
